export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";

export const GET_PRODUCTS_BEGIN = "GET_PRODUCTS_BEGIN";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR";

export const GET_SINGLE_PRODUCT_BEGIN = "GET_SINGLE_PRODUCT_BEGIN";
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS";
export const GET_SINGLE_PRODUCT_ERROR = "GET_SINGLE_PRODUCT_ERROR";

export const ADD_TO_CART = "ADD_TO_CART";
export const COUNT_CART_TOTALS = "COUNT_CART_TOTALS";
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";
export const TOGGLE_CART_ITEM_AMOUNT = "TOGGLE_CART_ITEM_AMOUNT";
export const INCREASE = "INCREASE";
export const DECREASE = "DECREASE";
export const CLEAR_CART = "CLEAR_CART";

export const TAKEOUT_SIDEBAR_OPEN = "TAKEOUT_SIDEBAR_OPEN";
export const TAKEOUT_SIDEBAR_CLOSE = "TAKEOUT_SIDEBAR_CLOSE";

export const PROFILE_SIDEBAR_OPEN = "PROFILE_SIDEBAR_OPEN";
export const PROFILE_SIDEBAR_CLOSE = "PROFILE_SIDEBAR_CLOSE";

export const CHECKOUT_INFO_LOAD = "CHECKOUT_INFO_LOAD";
export const CHECKOUT_INFO_SUCCESS = "CHECKOUT_INFO_SUCCESS";

export const GET_SPACES_SUCCESS = "GET_SPACES_SUCCESS";

export const IS_NOT_TAKEOUT_PAGE = "IS_NOT_TAKEOUT_PAGE";

export const SET_HEADER_THEME_NAME = "SET_HEADER_THEME_NAME";

export const LOGIN_LOAD = "LOGIN_LOAD";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";
